# Generated by Django 2.1.7 on 2019-03-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190317_0055'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='place',
        #     name='opening_hours',
        #     field=models.CharField(max_length=50),
        # ),
    ]
