# Generated by Django 2.1.7 on 2019-03-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190317_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='opening_hours',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
