# Generated by Django 2.1.7 on 2019-03-30 10:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_place_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 30, 10, 16, 26, 88540, tzinfo=utc)),
        ),
    ]
