# Generated by Django 2.2 on 2019-04-07 15:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20190404_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
