# Generated by Django 2.1.7 on 2019-03-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190405_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='map_id',
            field=models.CharField(max_length=500),
        ),
    ]
