# Generated by Django 2.1.7 on 2019-03-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190315_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='image',
            field=models.ImageField(default='none', upload_to=''),
            preserve_default=False,
        ),
    ]
