# Generated by Django 2.1.7 on 2019-03-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rating_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='image',
            field=models.ImageField(default='static/home/images/rating_stars/0_stars.png', upload_to=''),
        ),
    ]
