# Generated by Django 2.1.7 on 2019-03-18 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190319_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='place',
            name='location_lng',
        ),
    ]
