# Generated by Django 2.1.7 on 2019-03-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190319_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.TextField(default='This is a description box, please fill it with informations about the place.'),
            preserve_default=False,
        ),
    ]
