# Generated by Django 2.1.7 on 2019-03-20 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_place_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
