# Generated by Django 2.1.7 on 2019-03-30 10:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_place_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 30, 10, 31, 55, 110721, tzinfo=utc)),
        ),
    ]
