# Generated by Django 2.1.7 on 2019-04-02 20:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20190402_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 2, 20, 20, 50, 932142, tzinfo=utc)),
        ),
    ]
